### ISSUE TITLE
cool stuff

### ISSUE THREAD

**Issue by Nex4rius** [ShicKla/AuspexGateSystems#1]
Hello

Can I use your stuff in my program?
Specifically the chevrons?
https://github.com/ShicKla/AuspexGateSystems/blob/release/ags/glyphsMW.ff

You did that SOO MUCH better than me. https://github.com/Nex4rius/Nex4rius-Programme/blob/master/nexDHD/stargate/chevron.lua#L59
That would be really nice. :)

**Comment by ShicKla** [comment]
I do not mind, but they did take some work to make. So, please credit me or my program as the source.

**Comment by Nex4rius** [comment]
Yes of course.
Thanks you :)
