### ISSUE TITLE
[ENH] Show the result of getEnergyRequiredToDial for gates in the list

### ISSUE THREAD

**Issue by catalyticenzyme** [ShicKla/AuspexGateSystems#14]
AGS should show, next to the list of gates, the result of `getEnergyRequiredToDial` (i.e. the energy required to dial and keep it open, or the fact that its address is malformed—the latter part is especially handy for seeing at a glance which gates have dropped off the grid since you added them).

**Comment by ShicKla** [comment]
Added in commit e42afad48391323fd83f5ef9a344ecd93755a09c
