### ISSUE TITLE
[SECURITY ENH] Add kiosk mode to AGS

### ISSUE THREAD

**Issue by catalyticenzyme** [ShicKla/AuspexGateSystems#16]
Sometimes people will have a claimed base which is generally immune to griefing thanks to protection mods/plugins and allow people to visit, and have their dialing computer capable of being used by anyone so that guests can dial the gate to leave. However, it is possible in this situation to exit out of AGS (using the Quit button or a soft or hard interrupt), and proceed to get back to the shell of the computer in question, allowing you to create mischief by perverting its code. I have myself seen several bases and a server spawn that people assumed were secure against troublemakers thanks to FTB Claims, yet that had left dialing computers like this for public use, suggesting this particular problem is frequently overlooked by AGS users.

There should be a configuration option (I would call it "kiosk mode" by analogy to similar functions in real-life software) that causes soft and hard interrupts to be eaten and the Quit button to only work when an authorised user uses it, so that dialing computers left open to the public cannot be rooted.

(Soft interrupts are just events by name `interrupt` and can be eaten that way; hard interrupts are Lua errors originating out of the `pullSignal` call and, I assume, can be eaten by `pcall`ing it. It is possible to tell who is pressing the Quit button because the `touch` signal gives x, y, mouse button, and player name as arguments in that order. The authorised user, or list or matching function thereof, would have to be a configuration option—perhaps both enabling kiosk mode and setting authorised users can be rolled into one config option, `kioskOwner`(`s`), which enables kiosk mode if nonempty/non`nil`.)

**Comment by ShicKla** [comment]
Added, see version 1.1.6 of AGS Launcher, currently on dev branch.
