### ISSUE TITLE
IDC port option not present

### ISSUE THREAD

**Issue by MR-Spagetty** [ShicKla/AuspexGateSystems#17]
IDC port option not present
![image](https://user-images.githubusercontent.com/54694556/144363936-db0a4334-e522-47a6-9db4-6485dd95f1e8.png)
i haev tried changing in and out of the dev branch and it was not present in dev branch or normal branch after doing this

**Comment by ShicKla** [comment]
The option is only available if a network card is installed in the computer. Can you please confirm if there is a card install, because I am failing to recreate the issue.

**Comment by MR-Spagetty** [comment]
Ah knowing the people that own this computer that is probably the case

**Comment by MR-Spagetty** [comment]
this was infact why
