### ISSUE TITLE
Is there an offline version of the AGS installer?

### ISSUE THREAD

**Issue by JadianRadiator** [ShicKla/AuspexGateSystems#19]
Is there an offline version of the AGS installer?
I want to add it to my pack as a craftable disk.
But I also don't want to require the player to be online to install AGS on a computer.

**Comment by MR-Spagetty** [comment]
You would have to basically stick the repo in the floppy but that would limit them to a specific version when offline 1 way to create the disc would be make a floppy backup of a version of ags without any addresses and make that disc th3 disc with ags on it

**Comment by ShicKla** [comment]
The floppy disk created with the floppy back up tool, acts as an offline installer. Keep in mind AGS is under development, so it keep that in mind. It is always better to install from the internet.
