### ISSUE TITLE
Disable histroy

### ISSUE THREAD

**Issue by MR-Spagetty** [ShicKla/AuspexGateSystems#21]
Some way to disable the gate history for use on servers in public places to preven5 players from digging addresses out of the history of people that do not want to be found or the ability to lock non progrqm admin players from accessing the gate history

**Comment by ShicKla** [comment]
I am currently working on a security, and will have the option to only allow access to authorized users

**Comment by ShicKla** [comment]
Feature implemented in version 0.8.0
