### ISSUE TITLE
StarGate Map

### ISSUE THREAD

**Issue by lukasz4444** [ShicKla/AuspexGateSystems#24]
Please add address map which shows stargates on something like map example in attachment. And also add option to add stargate automatically just ping stargate and then that stargate wich reponse add to the list my 2 idea is so you can set radius to ping stargates and the program will ping every strgate in the readius and if that Stargate response it will add it to the list or specifed folder.

and i know that it can be too big program size to added to ags
but you can make addon for that that just is external program if file is too big.

ps. i know that radar image is from warp drive mod but it is just an example.

![radar example](https://user-images.githubusercontent.com/93074713/147371565-6499007e-9e0b-411f-896b-781e93d05be6.png)

**Comment by ShicKla** [comment]
The AUNIS OpenComputers API lacks the needed functionality to get the info to provide such a map. On that note this idea will be rejected.

**Comment by lukasz4444** [comment]
You didn't understand me correctly map is my idea nr 2 and yes you can do this you just need to make script that can ping every combination of stargate address and that stargates that reponse to ping add to the list of adresses.

If that is not possible you cannot check if stagate is on inputed adress but you added that funcionality to the script so it is posible.

So please add this @ShicKla.
