### ISSUE TITLE
Visual Error

### ISSUE THREAD

**Issue by lukasz4444** [ShicKla/AuspexGateSystems#25]
Closed iris is not showing on graphic of the gate.

**Comment by TheRedCreations** [comment]
This is not an error. It hasn't been added yet. But you can see the status of the Iris/Shield here: 
![grafik](https://user-images.githubusercontent.com/35812887/147510032-495cc287-2ec2-4c2e-98f2-8cbda09a5fd2.png)

**Comment by ShicKla** [comment]
There is no iris graphic at this time.
