### ISSUE TITLE
Ver 0.8.1 - Program crashes when click on Edit Entry without selected Entry

### ISSUE THREAD

**Issue by TheRedCreations** [ShicKla/AuspexGateSystems#26]
![grafik](https://user-images.githubusercontent.com/35812887/147506863-1319f8d7-21d4-4088-a698-7c0acfe65d0c.png)

**Comment by ShicKla** [comment]
I will look in to it and fix it in next update.

**Comment by ShicKla** [comment]
Now fixed in recent Dev build
