### ISSUE TITLE
Ver 0.8.1 - Add Entry bug

### ISSUE THREAD

**Issue by TheRedCreations** [ShicKla/AuspexGateSystems#27]
https://youtu.be/Aqir1lsFwFs

**Comment by ShicKla** [comment]
It seems to be working as intended. Are you by chance seeing something that I might be missing? Is it possible I might have caused confusion with my changes to how you add a gate entry?

**Comment by TheRedCreations** [comment]
Normally you was enter an Address before setting a Name to it. Now you add an Entry you get directly Asked for a name and you have to edit the Entry to add the missing address. Or am I wrong with something?

**Comment by ShicKla** [comment]
Your understanding of the new process is correct. You Add Entry >> Enter Name >> Add Gate Address
If you are wondering why it got changed, that short answer is optimization of the code and eliminate some odd behavior that was occurring.

**Comment by TheRedCreations** [comment]
k. then i'm going to work with the new process
