### ISSUE TITLE
Cannot dial

### ISSUE THREAD

**Issue by MR-Spagetty** [ShicKla/AuspexGateSystems#38]
![image](https://user-images.githubusercontent.com/54694556/150661227-b383a479-7612-4070-98d2-b8f1ecaa3e1b.png)
AGS 8.0 dev branch
for some reason, this computer will not allow me to dial I have rebooted this computer multiple times

**Comment by MR-Spagetty** [comment]
oops misread the version it is version 8.3 dev

**Comment by MR-Spagetty** [comment]
replacing stargate base block fixed the issue

**Comment by ShicKla** [comment]
Yeah I found that there is something weird happening with the gates. They are acting like they have an open wormhole, but they dont have one. So, the AGS is getting confused. I am going to wait and see what MineDragon does before I proceed with any fix
