### ISSUE TITLE
[AGS 0.8.0] Pegasus Gate DHD dial fails on engaging last chevron

### ISSUE THREAD

**Issue by TheRedCreations** [ShicKla/AuspexGateSystems#39]
https://youtu.be/Ry3l4PBx0C4

**Comment by ShicKla** [comment]
Interesting, this behavior did not occur in my testing. I will have to look in to it.

**Comment by ShicKla** [comment]
Okay I found out what was happening. The DHD did not have a glyph crystal installed and the computer is dialing an address that had more then 6 glyphs. I will have to update AGS to compensate for this scenario.

**Comment by TheRedCreations** [comment]
fk. I could have come up with the missing crystal myself

**Comment by ShicKla** [comment]
Fixed with commit abe7d73f3fed8567012d23f3835361ad6f5e8b5a
