### ISSUE TITLE
It will be very cool if there's an option to change appearance in AGS to something like this

### ISSUE THREAD

**Issue by lukasz4444** [ShicKla/AuspexGateSystems#4]
![iris closed](https://user-images.githubusercontent.com/93074713/139575878-28c01b74-1cf0-4798-a758-502f009c88ea.png)
![iris open](https://user-images.githubusercontent.com/93074713/139575879-f18c5247-e164-4d6c-b6ae-9b4361769970.png)
![incoming](https://user-images.githubusercontent.com/93074713/139575880-1451bef8-2982-4e18-96a2-0a76bf19aa1b.png)

**Comment by ShicKla** [comment]
Unfortunately Open Computers is very limited and can not support such graphics.

**Comment by lukasz4444** [comment]
but i don't mean animations i mean just look i know the animations are impossible but just appearance is possible.
