### ISSUE TITLE
Countdown to maximum lifespan is possible read the description

### ISSUE THREAD

**Issue by lukasz4444** [ShicKla/AuspexGateSystems#43]
yes it is possible if you can detect dhd and the stargate you can detect auto close. **By just monitoring close of the wormhole when it closes with no intereaction with dhd or pc.**

**You can to that because you can monitor power so you can know whre it is an autoclose or just power of the stargate goto 0%.**

**Or just user can wirte time in seconds to the file sectoautolose.lua as an example so yes you can add this @ShicKla .**

**Comment by MR-Spagetty** [comment]
Your suggestion was denied just accept that

**Comment by ShicKla** [comment]
As I mentioned in response to issue #42 I see no value in such a feature, and it will not be implemented.
