### ISSUE TITLE
GDO?

### ISSUE THREAD

**Issue by craft90** [ShicKla/AuspexGateSystems#45]
Hi! Now this might not be as much of an issue as an inquire. I was wondering if there's some sort of GDO implementation in the program? Like a tablet capable of transferring a IDC code to open a remote iris. I know that there's a IDC option already present... but as far as I can tell it works between computers only. I did try to make a tablet with the program but it requires a tier 3 screen which the tier 2 tablet doesn't support.

**Comment by MR-Spagetty** [comment]
Go read the roadmap and it also already has compatibility With basic oc messages and the GDO built in to the mod

**Comment by craft90** [comment]
The original AUNIS doesn't have a GDO though. Sure there's the Universe Dialer... but I don't understand its OpenComputer functionality. I'll check the road map though! If I can find it...

**Comment by craft90** [comment]
I also have no experience with LUA programing myself... so I don't know how to send OC messages...

**Comment by MR-Spagetty** [comment]
Use AUNIS: Resurrection it is the official continuation of AUNIS

**Comment by craft90** [comment]
I didn't know about that, thanks.
