### ISSUE TITLE
Remote Dialer

### ISSUE THREAD

**Issue by lukasz4444** [ShicKla/AuspexGateSystems#46]
Dialler for oc tablets that connect wireless to ags pc or server with ags.

**Comment by MR-Spagetty** [comment]
Planned
https://github.com/ShicKla/AuspexGateSystems/wiki#ags-tablet

**Comment by ShicKla** [comment]
> Dialler for oc tablets that connect wireless to ags pc or server with ags.

Please check roadmap before posting suggestions.
