### ISSUE TITLE
Redstone Card Crash

### ISSUE THREAD

**Issue by lukasz4444** [ShicKla/AuspexGateSystems#49]
**AGS crashes without Redstone Card.**

![redstone card error](https://user-images.githubusercontent.com/93074713/156621842-896d4f3f-9cea-462f-9737-e09c3cdca87d.png)

**Comment by ShicKla** [comment]
That is because you are running the development version of AGS, use the release version.
The development branch is for testing and may have partially implemented code. **Do Not Use** the development branch unless you were suggested to, or know what you are doing.
