### ISSUE TITLE
AGS medium

### ISSUE THREAD

**Issue by lukasz4444** [ShicKla/AuspexGateSystems#54]
**BEFORE YOU CLOSE THIS ISSUE I KNOW THERE IS AGS LITE PLANNED BUT THAT SOMETHING DIFFERENT.**

Program for low tier pc that is better than lite but still not enough for regular ags.

I found image that can show how it can look like.

![ags medium](https://user-images.githubusercontent.com/93074713/160448671-30a0248f-cc6e-427f-9e7e-4dd46913e25a.png)

**Comment by ShicKla** [comment]
Please learn what are within the capabilities of Open Computers before making any suggestions. For example that image you provided, even though looks blocky, would require OC Tier 3 Hardware to be displayed. I also do not appreciate you presenting someone else's dialing program, which they probably worked hard on, as a suggestion of what I should make my program to look like. It would be plagiarism and unethical for me to do such a thing.

I have already stated in my road map that I intend to develop a simpler version of the dialing program. Do not assume what the requirements will or will not be, at this time. Also do not assume what it will or will not look like.
