### ISSUE TITLE
Screen disconnect on Universe dial

### ISSUE THREAD

**Issue by craft90** [ShicKla/AuspexGateSystems#59]
**Describe the bug**
I attempted to dial with a universe gate to another universe gate. But when a chevron locked the screen flipped between showing the interface and just a blank screen.

Btw, I'm running a t3 computer with one (1) t3 screen. Specs are; t3 graphics card, internet card, redstone t2 card, t2 CPU, 2x 2.5 RAM and a t2 harddrive running AGS and OpenOS.

**To Reproduce**
1. Use a computer to dial from a Universe gate to another such gate.
2. When the second chevron locks, the screen goes black
3. When the third chevron locked, the screen came back online
4. Repeat
5. In the end the gate dialed out but the screen was blank. Going through the gate reset it back. However, with the screen blank I couldn't activate anything from the interface. I had to reset with the universe dialer.

**Expected behavior**
I expected to be able to follow the dialing process through the interface and then close the gate. Despise the screen "flickering" the dial process went through.

**Version of AUNIS being used**
Aunis: Resurrection, aunis-1.12.2-4.10.1.0-client.jar

**Comment by MR-Spagetty** [comment]
Have you tried not having the screen touching the computer case
Because the redstone functionality emits redstone signals when dialling and a redstone signal turns oc screens on and off

**Comment by ShicKla** [comment]
> Have you tried not having the screen touching the computer case Because the redstone functionality emits redstone signals when dialling and a redstone signal turns oc screens on and off

@craft90 This is most likely the cause of the issue. The sides in which the redstone outputs on can be changed in the dialer.cfg file in the ags directory. Alternatively you can use the OC redstone block adapter instead of having a card in the computer.
