### ISSUE TITLE
When you add somthing to favorites in ags you can't edit antything.

### ISSUE THREAD

**Issue by lukasz4444** [ShicKla/AuspexGateSystems#7]

**Comment by ShicKla** [comment]
Can you please clarify what you mean when you say you can't edit? If you are referring to editing a gate entry, I was unable to recreated what you are mentioning. I am going to need more details and explanation of what process leads to the issue.

**Comment by lukasz4444** [comment]
I mean add new entry, clear history or just move something up, after computer (from opencomputers) reboot any changes get deleted .

**Comment by ShicKla** [comment]
Unfortunately I am still unable to reproduce the issue. The problem may be unrelated to AGS, and I would recommend trying to see if happens on a fresh world. If the problem still persists can you provide me with a copy of your world save, and a list of mods or modpack you are using?

**Comment by lukasz4444** [comment]
Mods Ender io, aunis(fork) opencomputers draconic evolution without required libraries

Word save - it happends on every world including if i create new ones so it doesn't matter.

**Comment by ShicKla** [comment]
Since you are running AUNIS: Ressurection, you will need to use the development build of AGS. The command to run the dev version is `ags -d`

**Comment by ShicKla** [comment]
Was never able to repeat the reported bug. Issue will be closed.
