### ISSUE TITLE
Iris/Shield error

### ISSUE THREAD

**Issue by DeathToCountry** [ShicKla/AuspexGateSystems#8]
Hello there, I saw already that someone was having the issue with the Iris/Shield control button not showing up, I recently installed a mod that is essentially piggybacking off the original Aunis mod code, as it has Iris/Shield as well as the new Pegasus gate, I did break and re-place the Base block and regrettably it didn't change anything.

**Comment by ShicKla** [comment]
It is very well possible you are only running the release branch version of AGS. The iris/shield button is currently only available in development mode. To run dev mode use the command `ags -d`. Try that out, and let me know the results, thanks.

**Comment by DeathToCountry** [comment]
Yessir that'll do it thank You very much. Also just for future reference, if You desired to know, the name of the mod is Aunis: Resurrection
